---
# Instalace sudo, přidání usera ansible, přidání do sudo grupy

-
  # Hosts:
  hosts: all 
  user: root
  gather_facts: false
  strategy: free
  
  # Vars:
  
  # Tasks:
  tasks:
    - name: Instalace sudo
      package:
        name: sudo
        state: present
    - name: Přidání grupy ansible
      group:
        name: ansible         
    - name: Přidání usera ansible
      user:
        name: ansible 
        password: "{{ 'ansi1250' | password_hash('sha512') }}"
        groups: ansible
    - name: User ansible do sudoers bez hesla
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^ansible'
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'    
  
  #Handlers:
  
  #Roles:
  


...
