---
# Zkopiruje hotovy skript do /root/skripty (pokud existuje udela jeho backup)

- hosts: all
  user: ansible
#  user: root
  gather_facts: no
  strategy: free 
  become: yes

  tasks: 
  - name: Instalace mailutils
    package:
      name: mailutils
      state: present
  - name: Instalace exim4
    package:
      name: exim4
      state: present 
  - name: Vytvori /root/skripty pokud neexistuje
    file: 
      path: "/root/skripty"
      state: directory       
  - name: Copy file with backup
    copy:
      src: mezisklad/root/skripty/apt-mail
      dest: /root/skripty/apt-mail
      backup: yes
...        
