---
# Zkopiruje hotovy skript do /root/skripty (pokud existuje udela jeho backup)

- hosts: all
  user: root 
#  user: ansible
  gather_facts: yes
#  become: yes

  tasks: 
  - name: Copy file with backup
    copy:
      src: mezisklad/root/skripty/apt-mail
      dest: /root/skripty/apt-mail
      backup: yes
             
...        
