---
# Instalace apache2 webserveru

-
  # Hosts:
  hosts: all 
  user: ansible
#  user: root
  gather_facts: no
  strategy: free 
  become: yes
  
  # Vars:
  
  # Tasks:
  tasks:
    - name: Instalace apache2
      package:
        name: apache2
        state: present
  
  #Handlers:
  
  #Roles:
  


...
